### ISSUE TITLE
Story download from chyoa which contains images is not working

### ISSUE THREAD

**Issue by choeronline** [theslavicbear/Ebook-Publisher#57]
Here is the error, I am getting while downloading story from choya which contains images:

> Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/ebook-publisher/Ebook-Publisher.py", line 187, in MakeClass
    formats[ft](site)
  File "/ebook-publisher/Ebook-Publisher.py", line 32, in <lambda>
    'epub':lambda x:MakeEpub(x),
  File "/ebook-publisher/Ebook-Publisher.py", line 158, in MakeEpub
    zeros = '0' * (len(str(site.isize))-1)
AttributeError: 'Chyoa' object has no attribute 'isize'

**Comment by theslavicbear** [comment]
This should be fixed now as of commit b93afd6b1f68aeb72e187d3a96c89e2cbf31dee4
