### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by labriochedu91** [theslavicbear/Ebook-Publisher#82]
what i give:

C:\Users\bn>Ebook-Publisher.py https://chyoa.com/chapter/namechapter -o epub -o html -d D:\test

what i get:

D:\téléchargements\Ebook-Publisher-master\Ebook-Publisher-master\bs4\element.py:15: UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.
  warnings.warn(
The Gamer, Chyoa edition.
[' Funatic']
When he turned 18, John Newman received a gift from Gaia the world spirit. Starting now his whole life would become a video game. Follow him as he discovers his new powers and use them for his own purposes. Unlike what happens in the original The Gamer has some other priorities and will develop his powers to have a lot of fun with the ladies around him.
968/1117 86%Traceback (most recent call last):
  File "D:\téléchargements\Ebook-Publisher-master\Ebook-Publisher-master\Ebook-Publisher.py", line 323, in <module>
    clas=MakeClass(i)
  File "D:\téléchargements\Ebook-Publisher-master\Ebook-Publisher-master\Ebook-Publisher.py", line 195, in MakeClass
    site=sites[domain](url)
  File "D:\téléchargements\Ebook-Publisher-master\Ebook-Publisher-master\Ebook-Publisher.py", line 19, in <lambda>
    'chyoa.com':lambda x:Chyoa.Chyoa(x),
  File "D:\téléchargements\Ebook-Publisher-master\Ebook-Publisher-master\Site\Chyoa.py", line 169, in __init__
    self.AddPrevPage(i.get('href'))
  File "D:\téléchargements\Ebook-Publisher-master\Ebook-Publisher-master\Site\Chyoa.py", line 351, in AddPrevPage
    self.AddPrevPage(i.get('href'))
  File "D:\téléchargements\Ebook-Publisher-master\Ebook-Publisher-master\Site\Chyoa.py", line 351, in AddPrevPage
    self.AddPrevPage(i.get('href'))
  File "D:\téléchargements\Ebook-Publisher-master\Ebook-Publisher-master\Site\Chyoa.py", line 351, in AddPrevPage
    self.AddPrevPage(i.get('href'))
  [Previous line repeated 964 more times]
  File "D:\téléchargements\Ebook-Publisher-master\Ebook-Publisher-master\Site\Chyoa.py", line 326, in AddPrevPage
    page = Common.RequestPage(url)
  File "D:\téléchargements\Ebook-Publisher-master\Ebook-Publisher-master\Site\Common.py", line 139, in RequestPage
    response = RequestSend(url, headers)
  File "D:\téléchargements\Ebook-Publisher-master\Ebook-Publisher-master\Site\Common.py", line 133, in RequestSend
    response = requests.get(url)
  File "C:\Users\bn\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\bn\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\bn\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\bn\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 677, in send
    history = [resp for resp in gen]
  File "C:\Users\bn\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "C:\Users\bn\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 237, in resolve_redirects
    resp = self.send(
  File "C:\Users\bn\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\bn\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\bn\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\bn\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\bn\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\bn\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1371, in getresponse
    response.begin()
  File "C:\Users\bn\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 338, in begin
    self.headers = self.msg = parse_headers(self.fp)
  File "C:\Users\bn\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 237, in parse_headers
    return email.parser.Parser(_class=_class).parsestr(hstring)
  File "C:\Users\bn\AppData\Local\Programs\Python\Python39\lib\email\parser.py", line 67, in parsestr
    return self.parse(StringIO(text), headersonly=headersonly)
  File "C:\Users\bn\AppData\Local\Programs\Python\Python39\lib\email\parser.py", line 56, in parse
    feedparser.feed(data)
  File "C:\Users\bn\AppData\Local\Programs\Python\Python39\lib\email\feedparser.py", line 176, in feed
    self._call_parse()
  File "C:\Users\bn\AppData\Local\Programs\Python\Python39\lib\email\feedparser.py", line 180, in _call_parse
    self._parse()
  File "C:\Users\bn\AppData\Local\Programs\Python\Python39\lib\email\feedparser.py", line 295, in _parsegen
    if self._cur.get_content_maintype() == 'message':
  File "C:\Users\bn\AppData\Local\Programs\Python\Python39\lib\email\message.py", line 594, in get_content_maintype
    ctype = self.get_content_type()
  File "C:\Users\bn\AppData\Local\Programs\Python\Python39\lib\email\message.py", line 578, in get_content_type
    value = self.get('content-type', missing)
  File "C:\Users\bn\AppData\Local\Programs\Python\Python39\lib\email\message.py", line 471, in get
    return self.policy.header_fetch_parse(k, v)
  File "C:\Users\bn\AppData\Local\Programs\Python\Python39\lib\email\_policybase.py", line 316, in header_fetch_parse
    return self._sanitize_header(name, value)
  File "C:\Users\bn\AppData\Local\Programs\Python\Python39\lib\email\_policybase.py", line 287, in _sanitize_header
    if _has_surrogates(value):
  File "C:\Users\bn\AppData\Local\Programs\Python\Python39\lib\email\utils.py", line 57, in _has_surrogates
    s.encode()
RecursionError: maximum recursion depth exceeded while calling a Python object

i don't speak english programam. HELP

**Comment by labriochedu91** [comment]
my bad! i didn't see #81 but i dont understand english and MTL dosent work. need esay words

**Comment by theslavicbear** [comment]
Are you using the latest release 3.2.0? For long stories like The Gamer, I suggest cloning the latest code from the update branch.
https://github.com/theslavicbear/Ebook-Publisher/tree/feature-3.3
