### ISSUE TITLE
Chyoa image download issue

### ISSUE THREAD

**Issue by theslavicbear** [theslavicbear/Ebook-Publisher#96]
I managed to fix that probelm by adding in my usr name and password. Only question i have is im having trouble adding images. i just cant get it to work. for this story i can only get the heading image https://chyoa.com/chapter/Introduction.817852 and for these stories https://chyoa.com/chapter/Introduction.332890 https://chyoa.com/chapter/Introduction.522981 i get 
this Traceback (most recent call last):
  File "C:\Users\Hp\Documents\Ebook-Publisher-master\Ebook-Publisher-master\Ebook-Publisher.py", line 343, in <module>
    formats[ft](clas)
  File "C:\Users\Hp\Documents\Ebook-Publisher-master\Ebook-Publisher-master\Ebook-Publisher.py", line 30, in <lambda>
    'HTML':lambda x:MakeHTML(x),
  File "C:\Users\Hp\Documents\Ebook-Publisher-master\Ebook-Publisher-master\Ebook-Publisher.py", line 48, in MakeHTML
    published=open(wd+title_stripped+'/'+site.title+'.html', 'w', encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Hp\\Documents\\Ebook-Publisher-master\\Ebook-Publisher-master\\./Idius Halfhwit and the Aegis of Probability/Idius Halfhwit and the Aegis of Probability.html'
PS C:\Users\Hp\Documents\Ebook-Publisher-master\Ebook-Publisher-master>

_Originally posted by @adwag-hue in https://github.com/theslavicbear/Ebook-Publisher/issues/92#issuecomment-2130615012_

**Comment by theslavicbear** [comment]
The image insertion for the first link seems to work fine when using the -t command, which vexes me as both variants use the same code to find the image links. Will keep looking into this.

**Comment by theslavicbear** [comment]
Okay I figured out the issue with the first link, will be fixed in next patch release.

**Comment by theslavicbear** [comment]
I wasn't able to reproduce the error with the other two links. Request you to pull the latest code and try them again. The first link should get all the images now.

**Comment by adwag-hue** [comment]
Thank you so much. I'm still having errors for some stories though. like this one https://chyoa.com/chapter/Introduction.600533 i do python Ebook-Publisher.py https://chyoa.com/chapter/Introduction.600533 -i --insert-images -o HTML --usr **** --pswd ****  i got this Traceback (most recent call last):
  File "C:\Users\Hp\Downloads\Ebook-Publisher-master\Ebook-Publisher-master\Ebook-Publisher.py", line 339, in <module>
    clas=MakeClass(i)
  File "C:\Users\Hp\Downloads\Ebook-Publisher-master\Ebook-Publisher-master\Ebook-Publisher.py", line 202, in MakeClass
    site=sites[domain](url)
  File "C:\Users\Hp\Downloads\Ebook-Publisher-master\Ebook-Publisher-master\Ebook-Publisher.py", line 21, in <lambda>
    'chyoa.com':lambda x:Chyoa.Chyoa(x),
  File "C:\Users\Hp\Downloads\Ebook-Publisher-master\Ebook-Publisher-master\Site\Chyoa.py", line 103, in __init__
    self.authors.insert(0,soup.find('p', class_='meta').find('a').get_text())
AttributeError: 'NoneType' object has no attribute 'get_text'
